### ISSUE TITLE
能不能做个基础模板文件？

### ISSUE THREAD

**Issue by yxy** [greyli/bootstrap-flask#1]
能否帮忙做个 base.html 给项目里直接引用

**Comment by greyli** [comment]
不添加内置的基模板是这个扩展的基本设计，因为内置基模板不够灵活，而且引入了不必要的复杂度。建议你自己在项目中创建基模板。

**Comment by zhang0peter** [comment]
不用做一个模板文件，但要做一个好看的样例，不然没人用

**Comment by greyli** [comment]
嗯，考虑在示例程序中添加一个完整的页面示例。我先把这个issue关闭了，如果有后续问题可以重新打开。
