### ISSUE TITLE
Missing support for FormFields

### ISSUE THREAD

**Issue by madsmtm** [greyli/bootstrap-flask#10]
First off, thanks for taking on the job as maintainer! 🎉 🎉 

Now to the bug: The jinja function `form_field` is not set in [`templates/bootstrap/form.html#L82`](https://github.com/greyli/bootstrap-flask/blob/master/flask_bootstrap/templates/bootstrap/form.html#L82):
Seems like a leftover after the transition

**Comment by greyli** [comment]
Thanks for the feedback! I will fix it then release a new version today.

**Comment by greyli** [comment]
Fixed in [1.0.8](https://github.com/greyli/bootstrap-flask/releases/tag/1.0.8).
