### ISSUE TITLE
Benefits  vs manual application?

### ISSUE THREAD

**Issue by MrBillium** [greyli/bootstrap-flask#101]
I looked through the documentation and this package definitely  looks like it helps with macros. But does it allow me to do anything in Flask that is not possible or easy to do manually with Bootstrap4 classes?

 I know I can tag my html with BS classes and  inject Bootstrap into WTFoms fields using class_= 

 ```
 <div class="form-group">
    <label for="password">Password</label>
      {{form.password (class_="form-control", id="password" ) }}
  </div>`
```

Are there problems with BS and Flask that this package will solve or is it mainly for coding ease  & convenience?

Sorry if I sound like a troll - I am just trying to understand the benefits  vs just applying Bootstrap across my site manually before diving in.

**Comment by greyli** [comment]
In general, this package is just a collection of Jinja macros, you don't need it if you want to write Bootstrap class manually. It just helps you to render Bootstrap-markup HTML more easily with built-in macros. For example, given a Flask-WTF's `Form` object, you can do:

```jinja2
{{ render_form(form) }}
```
Given a Flask-SQLAlchemy's `pagination` object, you can do:
```jinja2
{{ render_pagination(pagination) }}
```

**Comment by MrBillium** [comment]
Ok thanks - I will probably stick with manual for now
