### ISSUE TITLE
how to control the num of li in the pagination ?

### ISSUE THREAD

**Issue by wo-ni** [greyli/bootstrap-flask#102]
how to control the num of li in the pagination?

**Comment by TitaniumHocker** [comment]
You can specify number of objects per page when creating `SQLAlchemy` pagination object.
See code from example of this package:
https://github.com/greyli/bootstrap-flask/blob/master/examples/app.py#L111

**Comment by wo-ni** [comment]
i wish add kwargs to ` pagination.iter_pages()  `,and we can control the length of pagination in the page.
