### ISSUE TITLE
Navbar color mismatches with Bootswatch Darkly

### ISSUE THREAD

**Issue by PanderMusubi** [greyli/bootstrap-flask#105]
When using https://bootswatch.com/darkly/ with a navbar that has `navbar-dark bg-dark` to get a white/grey text on dark background results in white/dark green text on light green background.

Using `navbar-light bg-secondary` or `navbar-light bg-succes` results in white/grey text on a background color that almost as the desired background color `dark` but this is not sufficiently solving the issue.

Is this an issue here or for Bootswatch?

**Comment by ziddey** [comment]
Can you provide sample code? You need to use `nav-` classes for the nav contents.

`render_nav_item` adds the appropriate `nav-item` and `nav-link` classes.

**Comment by greyli** [comment]
This extension won't affect the navbar style by any means, you may need to report this for Bootswatch.
