### ISSUE TITLE
bootswatch css link missing '>'

### ISSUE THREAD

**Issue by Demetriex** [greyli/bootstrap-flask#110]
https://github.com/greyli/bootstrap-flask/blob/3c8de07e3c3cc9e6440e8b6d46bc94f40d29d000/flask_bootstrap/__init__.py#L93-L94

**Comment by greyli** [comment]
[Fixed](https://github.com/greyli/bootstrap-flask/commit/5d80b53ec4a731d008cabb567cfd010f407837d9) and released with 1.5.1, thanks.
