### ISSUE TITLE
Example does not fully work out of the box (anymore?)

### ISSUE THREAD

**Issue by WolfgangFahl** [greyli/bootstrap-flask#113]
I tried to follow the instructions in https://github.com/greyli/bootstrap-flask/tree/master/examples

my environment is:
``` bash
python --version
Python 3.8.6
```
on Mac OS 10.13.6

The webapp starts fine and the main screen shows:
![grafik](https://user-images.githubusercontent.com/1336221/104116545-c5a2ca00-5319-11eb-8fe0-8e48f2e658be.png)

The pagination tab / route gives an Internal Server Errror with the log showing:

```
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) NOT NULL constraint failed: message.text
[SQL: INSERT INTO message (text, author, category, draft, create_time) VALUES (?, ?, ?, ?, ?)]
[parameters: (None, None, None, 0, None)]
```

The static tab is empty but seem to try to load some js and css files with no visible effect.

The table tab show empty tables. There seems to be a need for loading data and i couldn't find a description what steps prefills the messages table.

**Comment by WolfgangFahl** [comment]
https://github.com/WolfgangFahl/pyFlaskBootstrap4/commit/b6ffb7a62a23f98cb55701a2a730d5fb15a713d5 seesm to improve things a bit. At least some table content shows now even if the logic seems to be broken.
![grafik](https://user-images.githubusercontent.com/1336221/104120235-710d4800-5335-11eb-872d-18f812d7983c.png)

**Comment by WolfgangFahl** [comment]
see https://github.com/WolfgangFahl/pyFlaskBootstrap4/commit/dda4719e0927689c7c8f919971787d8cc79a43ce
![grafik](https://user-images.githubusercontent.com/1336221/104120917-cd269b00-533a-11eb-9431-4fe2d7d2f57f.png)

**Comment by greyli** [comment]
Thanks for the report. Fixed in [this commit](https://github.com/greyli/bootstrap-flask/commit/d8d4610d49e14bd5193ae5d422a921b290dfba3b).
