### ISSUE TITLE
load_css() 和 load_js() 因为端点错误不能正确的使用本地资源

### ISSUE THREAD

**Issue by Dnsayhey** [greyli/bootstrap-flask#121]
你好，我在app的配置中，BOOTSTRAP_SERVE_LOCAL = True 已经成功的设置了。
但是在bootstrap-flask中的load_css()和load_js()方法中，在判断以上配置为True的时候，貌似配置的端点是bootstrap.static而不是static，结果引用的依然是cdn资源，我进行如下修改之后效果正常了。
![image](https://user-images.githubusercontent.com/37830769/110890172-76354600-832a-11eb-82ba-75eeca0b60d3.png)

**Comment by greyli** [comment]
另外附上几点小建议：

- 问问题要给出相关代码，比如「我在app的配置中，BOOTSTRAP_SERVE_LOCAL = True 已经成功的设置了」，不要假设自己的代码是对的，把代码贴出来别人可以帮你判断
- 不要假设自己得到的结论是正确的，而要给出相关依据，比如「结果引用的依然是cdn资源」
- 不要用图片贴代码，而要用纯文本
- 对于非中文项目（README 和 文档都仅提供中文的项目），用英文发 issue，用翻译软件也可以。如果不想用英文，可以把问题发到 [HelloFlask 论坛](https://discuss.helloflask.com)

**Comment by Dnsayhey** [comment]
好的，谢谢指正。
