### ISSUE TITLE
`render_table` macro broken with new version of sqlalchemy

### ISSUE THREAD

**Issue by Demetriex** [greyli/bootstrap-flask#123]
The example should work properly without the title.

if you run the example in debug mode the error says 'AttributeError: _data'.

https://github.com/greyli/bootstrap-flask/blob/04c023601ce875b7ad38aa26957a4302123551f4/flask_bootstrap/__init__.py#L33

the `get_table_titles` function is broken with `sqlalchemy>=1.4.0`

_Originally posted by @Demetriex in https://github.com/greyli/bootstrap-flask/issues/122#issuecomment-803741942_

**Comment by junmoxiao** [comment]
I have the same problem.

**Comment by greyli** [comment]
I will take a look into it next week then make a new release. PR is welcome.

For a temporary fix, you can downgrade the version of SQLAlchemy:

```
pip install -U sqlalchemy==1.3.24
```

**Comment by greyli** [comment]
Just released [1.5.2](https://github.com/greyli/bootstrap-flask/releases/tag/1.5.2) to fix this, give it a try!
