### ISSUE TITLE
no example about button_map dictionary in the render_field macro

### ISSUE THREAD

**Issue by meizhaohui** [greyli/bootstrap-flask#13]
Hi,Greyli:
I am try to use the new Bootstrap-flask to build my website. And try to understand to examples.
when I read the render_field(field, form_type="basic", horizontal_columns=('lg', 2, 10), button_map={}) part. I try to use the form.html example to check the method.
There are four render_field in the example. I try to add the button_map={} into the render_field.
{{ render_field(form.username) }}
{{ render_field(form.password) }}
{{ render_field(form.remember) }}
{{ render_field(form.submit) }}

for example:
{{ render_field(form.submit, button_map={form.submit:'success'}) }}   --> not work!
{{ render_field(form.submit, button_map={'form.submit':'success'}) }}    --> not work!
{{ render_field(form.submit, button_map={'submit':'success'}) }}    --> work!!!
{{ render_field(form.submit, button_map={'submit':'danger'}) }}    --> work!!!
{{ render_field(form.submit, button_map={'submit':'info'}) }}    --> work!!!
{{ render_field(form.submit, button_map={'submit':'primary'}) }}    --> work!!!

Then I think,we should add the example how to make the button_map mapping dictionary in the docs.

If I change class HelloForm(FlaskForm) in the app file submit = SubmitField()  to  upload = SubmitField(), Then if the form.html should change the render_field method .
{{ render_field(form.submit, button_map={'submit':'primary'}) }} will change to {{ render_field(form.upload, button_map={'upload':'primary'}) }}.

Then it will work. I suggest to add this example. Thanks.

**Comment by greyli** [comment]
Thanks for the feedback. The usage for `button_map` was actually covered in the [documentation](https://bootstrap-flask.readthedocs.io/en/latest/macros.html#render_form). I just added an example to the docstring: 

> button_map – A dictionary, mapping button field names to names such as `primary`, `danger` or `success`. For example, `{'submit': 'success'}`. Buttons not found in the `button_map` will use the default type of button.

**Comment by greyli** [comment]
I’ll close this issue for now. Please feel free to comment further or re-open this issue if you wish.
