### ISSUE TITLE
Considering change the default action_pk_placeholder in render_table() from `:primary_key` to `:id`

### ISSUE THREAD

**Issue by greyli** [greyli/bootstrap-flask#135]
I'm thinking of changing the default action pk placeholder from `:primary_key` to `:id`. `:id` is short and easy to type, and the user usually uses `id` or `foo_id` in their route URL rules to represent the primary key variable.

Hi @michaelbukachi, what do you think? Any particular reason to use `:primary_key` in #77?

**Comment by michaelbukachi** [comment]
@greyli I think it's fine. I don't think there was any particular reason why I used `:primary_key` instead of `:id` :thinking: . I think it was a 'spur-of-the-moment' decision.

**Comment by caffeinatedMike** [comment]
Semi-related (or maybe not). The action url routes currently cannot contain variable types or they will not work with the macro. Example: `@app.route("/a/<int:b>/c")`

**Comment by greyli** [comment]
Ok, I will make the change with a warning, then remove the support to the old value in the next major version.
