### ISSUE TITLE
Support title and desc in resulting svg for render_icon

### ISSUE THREAD

**Issue by PanderMusubi** [greyli/bootstrap-flask#154]
Please, support optional title and optional desc for `render_icon`. This is similar as adding an alt attribute to an img. See also https://css-tricks.com/accessible-svgs/#2-inline-svg Advantage is that the text can be read out loud for people who need e.g. text2speech while browsing.

**Comment by PanderMusubi** [comment]
Please review https://github.com/greyli/bootstrap-flask/pull/168

**Comment by PanderMusubi** [comment]
Do the `if` and `endif` need to be on separate lines?

**Comment by PanderMusubi** [comment]
Moved to separate lines and added documentation in the PR.

**Comment by greyli** [comment]
Implemented in #172
