### ISSUE TITLE
Update macros for Bootstrap 5

### ISSUE THREAD

**Issue by greyli** [greyli/bootstrap-flask#162]
The initial support for Bootstrap 5 was added in #161. Then I'll update all the macros to support Bootstrap 5:

- [x] render_messages
- [x] render_icon
- [x] render_static
- [x] render_nav_item
- [x] render_breadcrumb_item
- [x] render_table
- [x] render_pager
- [x] render_pagination
- [x] render_field
- [x] render_form
- [x] render_form_row
- [x] render_hidden_errors

Feel free to make a PR for some of the macros!

**Comment by PanderMusubi** [comment]
When working on `render_field`, please also have a look at https://github.com/greyli/bootstrap-flask/pull/174#issue-1050912486
