### ISSUE TITLE
Warning by linter on assert in test_render_messages.py

### ISSUE THREAD

**Issue by PanderMusubi** [greyli/bootstrap-flask#169]
Warning by linter on assert in test_render_messages.py on line https://github.com/greyli/bootstrap-flask/blob/master/tests/test_bootstrap4/test_render_messages.py#L53

The warning is: `W0129 (assert-on-string-literal) line 53: Assert statement has a string as its first argument. The assert will never fail.`

**Comment by greyli** [comment]
That line has a typo, it should be:

```
assert 'alert-dismissible' in data
```

**Comment by PanderMusubi** [comment]
Fxied in https://github.com/greyli/bootstrap-flask/pull/173
