### ISSUE TITLE
Add Bootstrap 5 support for range fields

### ISSUE THREAD

**Issue by greyli** [greyli/bootstrap-flask#190]
Originally from https://github.com/greyli/bootstrap-flask/pull/187#issuecomment-996972531

**Comment by greyli** [comment]
Hi @PanderMusubi, could you take a look at this?

**Comment by PanderMusubi** [comment]
Testing master example Bootstrap5 I get this error for navigating to form:

    jinja2.exceptions.TemplateNotFound: bootstrap5/form.html

**Comment by greyli** [comment]
Please post the full error traceback.

**Comment by PanderMusubi** [comment]
Ah, fixed it. Missed a step in the installation. It works but the range does not yet look like the ones in https://getbootstrap.com/docs/5.1/forms/range/

The horizontal line is missing and the control is a larger circle without color.

**Comment by greyli** [comment]
As you said [here](https://github.com/greyli/bootstrap-flask/pull/187#issuecomment-996972531), I think the form-range class should be used for range fields.

**Comment by PanderMusubi** [comment]
Yes, think so too.

**Comment by PanderMusubi** [comment]
Tested and confirmed
