### ISSUE TITLE
Bootstrap requires Popper.js

### ISSUE THREAD

**Issue by derlin** [greyli/bootstrap-flask#2]
When using `bootstrap.load_js()`, the _popper_ script is included __after__ bootstrap, ending with 

> Bootstrap <component> requires Popper.js 

when using dropdowns, etc. A simple fix is to change the order of Markup in the last line of `__init__.py`:

```
# render popper before js
return Markup('%s\n%s\n%s\n' % (jquery, popper, js))
```

**Comment by greyli** [comment]
Thanks, I' ll fix it and release a new version late in the day.

**Comment by greyli** [comment]
Version [1.0.2](https://github.com/greyli/bootstrap-flask/releases/tag/1.0.2) released. Thanks again.
