### ISSUE TITLE
Form doesn't work on example

### ISSUE THREAD

**Issue by jdlynn** [greyli/bootstrap-flask#20]
I installed the example as directed in the documentation.  When I run the Form example I get the error:

jinja2.exceptions.UndefinedError: the template 'bootstrap/form.html' (imported on line 2 in 'form.html') does not export the requested name 'render_form_row'_**

Everything else in the example appears to work.

**Comment by greyli** [comment]
Thanks for reporting on this, `render_form_row` is a new macro at master. I just release [1.0.10](https://pypi.org/project/Bootstrap-Flask/), please upgrade it:
```
pip install -U bootstrap-flask
```
then everything will be OK.
