### ISSUE TITLE
Fix typo in table form

### ISSUE THREAD

**Issue by PanderMusubi** [greyli/bootstrap-flask#206]
See Cutomized -> Customized :
- https://github.com/greyli/bootstrap-flask/blame/master/examples/bootstrap4/templates/table.html#L9
- https://github.com/greyli/bootstrap-flask/blame/master/examples/bootstrap5/templates/table.html#L9

**Comment by ez-sherlock** [comment]
Please assign this to me :)

**Comment by ez-sherlock** [comment]
@greyli I have pushed the changes and made a pull request. Please have a look. Thanks.
