### ISSUE TITLE
render_form,form_type='inline',label class is 'sr-only'

### ISSUE THREAD

**Issue by ieiu** [greyli/bootstrap-flask#25]
I use render_form with a wtforms.IntegerField and set form_type='inline'
then class of the label  in IntegerField is 'sr-only' and i can't see it 
is it a feature?

**Comment by greyli** [comment]
Please provide all the necessary source code.

**Comment by ieiu** [comment]
你好，上一次发帖后发现可以中文交流，那我还是不展示我崴脚的英文了
模板中的代码，表单类型为inline时出现此问题
![图片](https://user-images.githubusercontent.com/24524065/56847877-37539e00-6914-11e9-827c-986f19bbb5b3.png)

python中
![图片](https://user-images.githubusercontent.com/24524065/56847880-433f6000-6914-11e9-907a-85dc06ac191c.png)

渲染出来的页面源码以及效果，label的class为sr-only，看不见
![图片](https://user-images.githubusercontent.com/24524065/56847821-687f9e80-6913-11e9-8dac-0cddc604bae0.png)
![图片](https://user-images.githubusercontent.com/24524065/56847808-26565d00-6913-11e9-8a57-e92d12e1872d.png)
修改这里后问题解决了
![图片](https://user-images.githubusercontent.com/24524065/56847852-cb713580-6913-11e9-9824-368e56a850b8.png)

**Comment by greyli** [comment]
在行内表单里隐藏标签是默认行为（但对使用读屏软件的盲人访客需要「显示」标签，即 screen reader only ->`sr-only`），你可以通过添加 placeholder 来显示输入内容提示。

**Comment by ieiu** [comment]
好的，感谢回复
