### ISSUE TITLE
SQLALCHEMY startup issues

### ISSUE THREAD

**Issue by wordtracker** [greyli/bootstrap-flask#27]
Tried starting bootstrap-flask just now and saw these warnings pop up:

>  .../site-packages/flask_sqlalchemy/__init__.py:814: UserWarning: Neither SQLALCHEMY_DATABASE_URI nor SQLALCHEMY_BINDS is set. Defaulting SQLALCHEMY_DATABASE_URI to "sqlite:///:memory:".
  'Neither SQLALCHEMY_DATABASE_URI nor SQLALCHEMY_BINDS is set. '
.../__init__.py:835: FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True or False to suppress this warning.
  'SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and '

Am also getting some test warnings with Python 3.7.3.

> .../usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/case.py:615: ResourceWarning: unclosed file <_io.BufferedReader name='../web/bootstrap-flask-test2/flask_bootstrap/static/css/bootstrap.min.css'>
  testMethod()
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/case.py:615: ResourceWarning: unclosed file <_io.BufferedReader name='../web/bootstrap-flask-test2/flask_bootstrap/static/js/bootstrap.min.js'>
  testMethod()
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/case.py:615: ResourceWarning: unclosed file <_io.BufferedReader name='../web/bootstrap-flask-test2/flask_bootstrap/static/jquery.min.js'>
  testMethod()
ResourceWarning: Enable tracemalloc to get the object allocation traceback
............
----------------------------------------------------------------------
Ran 16 tests in 0.588s

OK

There doesn't seem to be any explanation about this in the docs. Please advise.

**Comment by wordtracker** [comment]
Am also getting some test warnings woth Python 3.7.3.
..../usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/case.py:615: ResourceWarning: unclosed file <_io.BufferedReader name='../web/bootstrap-flask-test2/flask_bootstrap/static/css/bootstrap.min.css'>
  testMethod()
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/case.py:615: ResourceWarning: unclosed file <_io.BufferedReader name='../web/bootstrap-flask-test2/flask_bootstrap/static/js/bootstrap.min.js'>
  testMethod()
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/unittest/case.py:615: ResourceWarning: unclosed file <_io.BufferedReader name='/Users/mikemindel/Projects/web/bootstrap-flask-test2/flask_bootstrap/static/jquery.min.js'>
  testMethod()
ResourceWarning: Enable tracemalloc to get the object allocation traceback
............
----------------------------------------------------------------------
Ran 16 tests in 0.588s

OK

**Comment by greyli** [comment]
Hi, thanks for reporting on this. The first issue was releated with Flask-SQLAlchemy, please check the [documentation](https://flask-sqlalchemy.palletsprojects.com/en/2.x/config/) for more information. As for the second issue, please provide the full error traceback.
