### ISSUE TITLE
quick_form macro

### ISSUE THREAD

**Issue by janwilamowski** [greyli/bootstrap-flask#28]
Thanks for providing an updated version of Flask-Bootstrap!

Flask-Bootstrap had some convenient macros as documented here: https://pythonhosted.org/Flask-Bootstrap/forms.html and implemented here: https://github.com/mbr/flask-bootstrap/blob/master/flask_bootstrap/templates/bootstrap/wtf.html

Specifically, the `quick_form` is quite handy. Would it be possible to add that?

**Comment by greyli** [comment]
Hi, the `quick_form` macro was renamed to `render_form`, you can import it from `bootstrap/form.html`.
