### ISSUE TITLE
Missing initial `<script =` tag

### ISSUE THREAD

**Issue by docsteveharris** [greyli/bootstrap-flask#3]
https://github.com/greyli/bootstrap-flask/blob/84802724ead7f859bf27ebbb73ab784155db3aba/flask_bootstrap/__init__.py#L86

**Comment by greyli** [comment]
Thanks to the feedback! It will be fixed really soon.

**Comment by greyli** [comment]
[Version 1.0.4](https://pypi.org/project/Bootstrap-Flask/1.0.4/) released.
