### ISSUE TITLE
flask_bootstrap.Bootstrap object' has no attribute 'load_css'

### ISSUE THREAD

**Issue by Shiqiu2019** [greyli/bootstrap-flask#30]
您好，没提过issue，不知道有没有走错地方，打扰了。<br>就是这个bootstrap-flask在自己的电脑里用得挺好的，但一挂到服务器上就报错。我把问题在[stackoverflow](https://stackoverflow.com/questions/57347802/flask-bootstrap-bootstrap-object-has-no-attribute-load-css)上提了，好像没人理我。过会儿到其他两个平台再问问。<br>因为是小白，想快速搭好一个好看点的网站，所以用了flask-bootstrap，现在卡死在这里了：）<br>
 希望能够帮忙解答一下，谢谢！

**Comment by greyli** [comment]
服务器上是不是同时安装了 Flask-Bootstrap？有的话需要卸载掉。

**Comment by Shiqiu2019** [comment]
> 服务器上是不是同时安装了 Flask-Bootstrap？有的话需要卸载掉。

谢谢！服务器上是同时安装了Flask-Bootstrap。我去卸载一下～
