### ISSUE TITLE
{{ bootstrap.load_css() }} 引入的CSS有问题

### ISSUE THREAD

**Issue by ryuutanyou** [greyli/bootstrap-flask#32]
{{ bootstrap.load_css() }} 引入的CSS有问题，那个css有错误，比如导航栏就显示不出来，我换了另外一个CDN可以显示正确，这个修复一下吧

**Comment by greyli** [comment]
@ryuutanyou Hello，默认使用的 Bootstrap 是 4.1 版本，确保你的 HTML 语法是对应版本？

**Comment by ryuutanyou** [comment]
css语法用的3.x版本，感谢

**Comment by greyli** [comment]
不客气，这个项目后面会增加对 Bootstrap 3 的向后支持。目前建议改用 Flask-Bootstrap。
