### ISSUE TITLE
cannot import name 'Bootstrap' from 'flask_bootstrap'

### ISSUE THREAD

**Issue by peterbayerle** [greyli/bootstrap-flask#35]
I'm having trouble using bootsrap-flask
using pip freeze I know that I have "Bootstrap-Flask==1.1.0" installed.
Here's my code:
```
from flask import Flask
from flask_bootstrap import Bootstrap
# ...

bootstrap = Bootstrap()
# ...
def create_app(config_name):
    app = Flask(__name__)
    app.config.from_object(config[config_name])

    bootstrap.init_app(app)
    # ...
    
    return app
```
And yet, I'm getting the error "cannot import name 'Bootstrap' from 'flask_bootstrap
". Anyone know why?

**Comment by angristan** [comment]
I have the same issue, did you figure it out?

**Comment by angristan** [comment]
Oh ok you have to uninstall `Flask-Bootstrap` *before* installing `bootstrap-flask`, if you remove it after it will break `bootstrap-flask`.

**Comment by udonjoku** [comment]
The doc is here for anyone who needs it. You need to MIGRATE from flask-bootstrap to Bootstrap-flask.

https://bootstrap-flask.readthedocs.io/en/latest/migrate/

**Comment by Areeb-Shahid** [comment]
Try to uninstall using this 
$ pip uninstall flask-bootstrap
$ pip uninstall flask-bootstrap bootstrap-flask

then use this 
$ pip install bootstrap-flask

if this doesn't work for you then go to the python packages search "bootstrap-flask" and click install it'll resolve your problem using Bootstrap5

**Comment by tarsisos** [comment]
> Oh ok you have to uninstall `Flask-Bootstrap` _before_ installing `bootstrap-flask`, if you remove it after it will break `bootstrap-flask`.

Hello @angristan, I did this you said, but I'm still having problem importing the package. How do you managed to use the bootstrap-flask? I also tried what Areeb-Shahid said, but didn't work also.

**Comment by PanderMusubi** [comment]
When I run `from flask_bootstrap import Bootstrap5` in `python3`, it works. To make sure you don't have any old versions, search with:

    sudo find / -name '*ootstrap*lask*'
    sudo find / -name '*lask*ootstrap*'

Remove what needs to be removed. Then install as normal user:

    pip install -U bootrstrap-flask

This should install version 2.3.0 at the time of writing. Let me know if it works now or what is the exact error.

**Comment by tarsisos** [comment]
Hello @PanderMusubi, yeah I tried here and worked 😅 But it's strange that the package isn't reconized. I forgot to mention that I'm using Windows 10, PowerShell and VS Code, studying through the book Flak Web Development.

Thank you!
