### ISSUE TITLE
render_pager(pagination),how to change lang for "Previous" and "Next"

### ISSUE THREAD

**Issue by jidanyu** [greyli/bootstrap-flask#36]
<img width="278" alt="屏幕快照 2019-11-03 下午2 34 20" src="https://user-images.githubusercontent.com/12640162/68081312-0c0fb580-fe47-11e9-8666-988571a57887.png">
noob question maybe. Please tell me how I can i change language. Thanks.

**Comment by greyli** [comment]
You can defined the button text with `next` and `prev` parameter. See https://bootstrap-flask.readthedocs.io/en/latest/macros.html#id10 for more details.
