### ISSUE TITLE
How can I add custom colors to navbar?

### ISSUE THREAD

**Issue by WhiteHeadbanger** [greyli/bootstrap-flask#37]
Hello, i've been trying to change the colors of the navbar, other than "navbar-light" or "navbar-dark". I want to make it from any color. 

I tried in several ways to use a base.css in a static folder, but I can't make it work. Is there a step by step guide to achieve this? I feel like the docs is not enough and it's needed an example of a custom widget.

**Comment by greyli** [comment]
Hi, you should check [Bootstrap's navbar documentation](https://getbootstrap.com/docs/4.3/components/navbar/) for widget customize. This project just provides some helper macro for Bootstrap.

**Comment by WhiteHeadbanger** [comment]
> Hi, you should check [Bootstrap's navbar documentation](https://getbootstrap.com/docs/4.3/components/navbar/) for widget customization. This project just provides some helper macro for Bootstrap.

Thanks!
