### ISSUE TITLE
Please Vote: Macro name for flashed messages

### ISSUE THREAD

**Issue by greyli** [greyli/bootstrap-flask#38]
I'm trying to implement a macro to render flashed messages, based on #5, which name do you think is best:

- 🎉  render_message
- ❤️  render_messages
- 🚀  render_flash_message
- 👀  render_flashed_messages

Thanks for voting!

**Comment by SobieskiCodes** [comment]
Assuming multiples can be made (of seperate types) render_messages makes the most sense to me.

**Comment by greyli** [comment]
OK, `render_messages` win...
