### ISSUE TITLE
Can you put the navigation definition in the PY file?

### ISSUE THREAD

**Issue by jackadam1981** [greyli/bootstrap-flask#42]
能否把导航定义放进py文件？
根据权限动态渲染导航菜单，也是很常见的需求。

Can you put the navigation definition in the PY file?

It is also a common requirement to dynamically render navigation menus according to permissions.

https://pythonhosted.org/flask-nav/advanced-topics.html#custom-elements
https://pythonhosted.org/flask-nav/advanced-topics.html#dynamic-construction

**Comment by greyli** [comment]
Closing this. After check out the Flask-Nav docs, I think it's too complicated to integrate it. I'll recommend you to create a fork of Flask-Nav, then make it work with Bootstrap 4.
