### ISSUE TITLE
Current commit on Github doesn't seem to match current version on pypi.

### ISSUE THREAD

**Issue by cxr5009** [greyli/bootstrap-flask#43]
render_messages looks to appear in the github bootstrap/utils.html macro but DOES NOT seem to appear in the current version available from pypi (pip3 install bootstrap-flask) (Bootstrap_Flask-1.1.0.dist-info)

**Comment by greyli** [comment]
The master branch does not release yet, I will upload it to PyPI today or tomorrow.

**Comment by greyli** [comment]
Version [1.2.0](https://pypi.org/project/Bootstrap-Flask/1.2.0/) released! Now you can update with `pip3 install -U bootstrap-flask`.
