### ISSUE TITLE
Decrease image file size

### ISSUE THREAD

**Issue by PanderMusubi** [greyli/bootstrap-flask#45]
The file size of the image in the documentation can be reduces by 25% by using `optipng` as can be found at https://github.com/an9uss/bootstrap-flask/pull/1

**Comment by greyli** [comment]
Thanks, you can just make a PR for this.

**Comment by PanderMusubi** [comment]
Here is the already existing PR https://github.com/an9uss/bootstrap-flask/pull/1

**Comment by PanderMusubi** [comment]
Can this PR be merged and issue get closed? Thanks.

**Comment by greyli** [comment]
You will need to fire a PR for this repo, not in your fork.

**Comment by PanderMusubi** [comment]
It was not my fork, but I will make a PR for it.

**Comment by PanderMusubi** [comment]
Here is a PR for it. https://github.com/greyli/bootstrap-flask/pull/65
