### ISSUE TITLE
Support Bootstrap icons

### ISSUE THREAD

**Issue by PanderMusubi** [greyli/bootstrap-flask#48]
Please support the recently released Bootstrap icons, see https://icons.getbootstrap.com/

**Comment by PanderMusubi** [comment]
Any progress/ideas on this issue? The Bootstrap icon set is actively maintained and growing fast in number of icons offered.

**Comment by greyli** [comment]
Since it doesn't support using the icon with CSS classes, I don't know how to implement this. Do you have a good idea?

**Comment by PanderMusubi** [comment]
Nope. Hence my request for support of Material Design icons that do support CSS in https://github.com/greyli/bootstrap-flask/issues/51

**Comment by PanderMusubi** [comment]
@greyli Does https://github.com/greyli/bootstrap-flask/issues/51 support CSS classes in the way you need to?
