### ISSUE TITLE
Support clipboardjs

### ISSUE THREAD

**Issue by PanderMusubi** [greyli/bootstrap-flask#49]
Made an implementation which supports clipboardjs by subclassing SubmitField as ClipboardField, passing three extra input parameters. I've extended the `form.html` template to render it and it works.

In the app code:

    class ClipboardField(SubmitField):
        def __init__(self, label=None, cb_value='', cb_cut=False, cb_text=False, **kwargs):
            super(ClipboardField, self).__init__(label, **kwargs)
            self.cb_value = cb_value
            self.cb_cut = cb_cut
            self.cb_text = cb_text
    
    class SortForm(FlaskForm):
        copy = ClipboardField('Kopieer', cb_value='words')
        cut = ClipboardField('Knip', cb_value='words', cb_cut=True)
        words = TextAreaField(default='aaa\nbbb)

In `form.html`:

    ...
        {%- elif field.type == 'ClipboardField' -%}
            {# deal with jinja scoping issues? #}
            {% set field_kwargs = kwargs %}
    
            {# note: same issue as above - should check widget, not field type #}
            {% call _hz_form_wrap(horizontal_columns, form_type, True, required=required) %}
                {# TODO support field_kw_args or implement by overriding field() #}
                <button class="btn btn-{{ button_map.get(field.name, 'light') }}"{% if field.cb_cut %} data-clipboard-action="cut"{% endif %} data-clipboard-{% if field.cb_text %}text="{{ field.cb_value|safe }}"{% else %}target="#{{ field.cb_value|safe }}"{% endif %}>{{ field.label.text|safe }}</button>
            {% endcall %}
        {%- elif field.type == 'SubmitField' -%}
    ...

It does require the following two lines to be added to the user template

    <script src="https://cdn.jsdelivr.net/npm/clipboard@2/dist/clipboard.min.js"></script>
    <script type="text/javascript">new ClipboardJS('.btn');</script>

What is a better way to implement this in bootstrap-flask so it is added behind the scenes?

**Comment by greyli** [comment]
IMO the usage of Clipboardjs is not so common, you can just use it directly in your project. Closing this, thanks.
