### ISSUE TITLE
Support Material Design Icons via Bootstrap

### ISSUE THREAD

**Issue by PanderMusubi** [greyli/bootstrap-flask#51]
Please support [Material Design Icons](http://materialdesignicons.com/bootstrap) via Bootstrap. See also https://github.com/twbs/bootstrap/issues/29860 and https://github.com/greyli/bootstrap-flask/issues/48

Motivation for supporting these icons is the combination of the design quality (based on Material Design) and the quantity obtained by remixing.

**Comment by PanderMusubi** [comment]
![a](https://user-images.githubusercontent.com/198964/70919087-7dcf4780-2020-11ea-8dff-c260f5bc00d0.png)

**Comment by greyli** [comment]
Bootstrap icons is preferred.
