### ISSUE TITLE
It seemed that render_kw in render_form is not working on the "class" property.

### ISSUE THREAD

**Issue by Great-Li-Xin** [greyli/bootstrap-flask#53]
https://github.com/greyli/bootstrap-flask/blob/9ca1e7f0a2d3233d781f23da23ad919901a09183/flask_bootstrap/templates/bootstrap/form.html#L235

My code here:

```
class RegistrationForm(FlaskForm):
    submit = SubmitField('Register', render_kw={'class': 'btn-primary'})
```

```
{% from 'bootstrap/form.html' import render_form %}

{{ render_form(form) }}
```

The return is quite confusing:
```
<input class="btn btn-secondary" id="submit" name="submit" type="submit" value="Register">
```

And it seemed that render_form is not passing the render_kw of the SubmitField to the rendered html. This made me confused.

**Comment by greyli** [comment]
Since we need to add Bootstrap classes when calling this macro in the template, the old class defined with `render_kw` will be overwritten. You can config button style with `button_map`:
```python
{{ render_form(form, button_map={'submit': 'primary'}) }}
```

**Comment by Great-Li-Xin** [comment]
@greyli Is it possible to append the `render_kw` after the Bootstrap classes? I consider this would be a much better way to achieve a more developer friendly solution.

**Comment by greyli** [comment]
Just fix this in https://github.com/greyli/bootstrap-flask/commit/708111a944081446b68c30c3166dfd41d868789e. Besides, [this PR](https://github.com/greyli/bootstrap-flask/pull/60) will bring a config called `BOOTSTRAP_BTN_STYLE`, you can use it to set a global button default style.
