### ISSUE TITLE
How to fix "jinja2.exceptions.UndefinedError: 'bootstrap_find_resource' is undefined"

### ISSUE THREAD

**Issue by sunhk25** [greyli/bootstrap-flask#57]
And downgrade to Flask-Bootstrap  3.3.7.1 will be OK.
I want to use bootstrap4,  but get the above error.

env\Lib\site-packages\flask_bootstrap\templates\bootstrap\base.html
<link href="{{bootstrap_find_resource('css/bootstrap.css', cdn='bootstrap')}}" rel="stylesheet">

**Comment by greyli** [comment]
You can't use this project with Flask-Bootstrap at the same time, try to uninstall Flask-Bootstrap and reinstall this one:
```
$ pip uninstall flask-bootstrap
$ pip install bootstrap-flask
```
