### ISSUE TITLE
Custom validation didn't display properly

### ISSUE THREAD

**Issue by samzhangjy** [greyli/bootstrap-flask#58]
你好！
I'm using Bootstrap-Flask to render a registration form, but the custom message for the DataRequired() validator still show up as the default message. It shows as excepted in `password2`, I guess it's because of EqualTo. My forms.py:
```python
# app/auth/forms.py

from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField
from wtforms.validators import DataRequired, Regexp, Email, Length, EqualTo


class RegistrationForm(FlaskForm):
    username = StringField('用户名', validators=[DataRequired(message='请输入用户名'), Regexp('^[A-Za-z][A-Za-z0-9_.]*$',
                                                                                     0, '用户名只能包含字母，数字，点'
                                                                                        '或下划线'), Length(1, 64)])
    email = StringField('邮箱', validators=[DataRequired(message='请输入邮箱'), Email(message='请输入真实的邮箱地址')])
    password = PasswordField('密码', validators=[DataRequired(message='请输入密码')])
    password2 = PasswordField('确认密码', validators=[DataRequired(message='请输入确认密码'), EqualTo('password',
                                                                                           message='密码不一致')])
    submit = SubmitField('注册')
```

Any ideas for this problem? Thanks!

**Comment by greyli** [comment]
Hi, I don't quite understand your words "the custom message for the DataRequired() validator still show up as the default message". Please explain *what you expect* and *what you actually get*. Post the screenshot will be helpful.

**Comment by samzhangjy** [comment]
Hi! What I expect is display the error messages I defined here - such as `请输入密码`. But what I got here is this:
<img width="1440" alt="Screen Shot" src="https://user-images.githubusercontent.com/56634385/78961199-46caf780-7b23-11ea-919a-15e10586af08.png">

It still display as the browser's default error message, but not the ones I wrote in my code. Thanks!

**Comment by greyli** [comment]
Bootstrap-Flask does nothing about this behavior. It's the HTML5's validate attribute ["required"](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/required) is working. 

Besides, when you use `DataRequired` validator, WTForms will generate form HTML with the `required` attribute as default:
```
>>> import wtforms
>>> from wtforms import Form, StringField
>>> from wtforms.validators import DataRequired
>>> class LoginForm(Form):
...     name = StringField('Name', validators=[DataRequired('hey, name is required!')])
>>> form = LoginForm()
>>> print(form.name)
<input id="name" name="name" required type="text" value="">  # <-- notice the required attr
```

**Comment by samzhangjy** [comment]
Oh... OK. Now I got it. Thanks a lot!

But by the way... I have another question. If I can't change the `required` attribute's text, then how can I display my custom error message instead of the default ones? Thanks!

**Comment by greyli** [comment]
If you use `render_form`, you can do `render_form(form, novalidate=True)`. Otherwise, you will need to put a `novalidate` attribute inside the `<form>` element:
```html
<form method="post" novalidate>
</form>
```

**Comment by samzhangjy** [comment]
Yes... Thank you very much!! I'll close this issue now.
