### ISSUE TITLE
I have problem with this app, i got TemplateNotFound: base.html

### ISSUE THREAD

**Issue by Michael2929** [greyli/bootstrap-flask#61]
sorry bother you guys:

I just did example code like yours, but i get a exception with TemplateNotFound: base.html.

I have to uninstall Bootstrap-Flask, and install flask-bootstrap, then it works for me, i dont know why this happen, can you fix it, thank you

**Comment by greyli** [comment]
Please post the full error traceback and related template code. In general, this extension doesn't come with a built-in base.html template, you have to [create one](https://bootstrap-flask.readthedocs.io/en/latest/basic.html#starter-template) by yourself.

**Comment by greyli** [comment]
Closing for inactive, feel free to reopen it if the problem still exists.

**Comment by aadejare** [comment]
> Please post the full error traceback and related template code. In general, this extension doesn't come with a built-in base.html template, you have to [create one](https://bootstrap-flask.readthedocs.io/en/latest/basic.html#starter-template) by yourself.

Link is gone

**Comment by PanderMusubi** [comment]
https://bootstrap-flask.readthedocs.io/en/latest/basic/#starter-template
