### ISSUE TITLE
1.3.0 adding an extra space to form field class attribute

### ISSUE THREAD

**Issue by coreybrett** [greyli/bootstrap-flask#63]
After updating to 1.3.0 I started getting the following JS error on one of my forms.

`jQuery.Deferred exception: An invalid or illegal string was specified create/<@http://localhost:5000/_static/libs/filepond-4-7-2/filepond.min.js:9:87915
create@http://localhost:5000/_static/libs/filepond-4-7-2/filepond.min.js:9:87875
D/<@http://localhost:5000/_static/libs/filepond-4-7-2/filepond.min.js:9:9772
Pr@http://localhost:5000/_static/libs/filepond-4-7-2/filepond.min.js:9:92198
Mr@http://localhost:5000/_static/libs/filepond-4-7-2/filepond.min.js:9:97464
Cr/<@http://localhost:5000/_static/libs/filepond-4-7-2/filepond.min.js:9:98908
Cr@http://localhost:5000/_static/libs/filepond-4-7-2/filepond.min.js:9:99006
e.create@http://localhost:5000/_static/libs/filepond-4-7-2/filepond.min.js:9:102387
@http://localhost:5000/_static/sdist/67435b6aa6ce2cf0e35dd319fb7967e9.js:2:402
l@http://localhost:5000/_static/js/libs/jquery-3.3.0.min.js:2:29375
a/</c<@http://localhost:5000/_static/js/libs/jquery-3.3.0.min.js:2:29677`

I traced this down to the upgrade from 1.2.0 to 1.3.0

The diff was...
```
<input class="form-control-file " id="file_" name="file_" type="file"> with 1.3.0
<input class="form-control-file" id="file_" name="file_" type="file"> with 1.2.0
```
Notice the extra space.

I was able to workaround the issue by adding `render_kw={"class": "xyz"}` to my form class.

**Comment by greyli** [comment]
Thanks for the report, just released [1.3.1](https://github.com/greyli/bootstrap-flask/releases/tag/1.3.1) to fix this issue.
