### ISSUE TITLE
Not getting form errors displayed for radio fields

### ISSUE THREAD

**Issue by coreybrett** [greyli/bootstrap-flask#69]
I'm using `{{render_form(form)}}` to display a form, but I'm not getting the errors displayed for them. If I `print(form.errors)` I see a dict with the errors.

**Comment by greyli** [comment]
Thanks for the report. [Fixed](https://github.com/greyli/bootstrap-flask/commit/6826895555351665b42a3b39ab861f69edee9d76) and released [1.3.2](https://pypi.org/project/Bootstrap-Flask/1.3.2/).
