### ISSUE TITLE
Support more macros

### ISSUE THREAD

**Issue by michaelbukachi** [greyli/bootstrap-flask#70]
Hello,
Nice library! I use it in a couple of projects.
Are there plans to add more macros to support more bootstrap 4 components? 
I have a couple in mind and would to do a PR or two.

**Comment by greyli** [comment]
Sure thing, what's your plan? It's better to discuss it first, since some components may do not need to write a macro.

**Comment by michaelbukachi** [comment]
Let's discuss it first. Yeah not all components need macros. I'm thinking of starting with complex components which would need macros. For instance tables. Maybe something along the lines of 
```
render_table(titles, data, bordered=False, ....)
```
Since you've added pagination already, I think it makes sense to proceed to tables.

**Comment by greyli** [comment]
Yeah, the `render_table` makes sense.

**Comment by michaelbukachi** [comment]
Awesome. I think I can start working on the `render_table` macro.

**Comment by WolfgangFahl** [comment]
The example already shows this but no content? What's needed to close this? See #113

**Comment by greyli** [comment]
Closing for now, feel free to make a PR/issue for new macro.
