### ISSUE TITLE
{% from 'bootstrap/table.html' import render_table %} fail

### ISSUE THREAD

**Issue by Raphael-Tu** [greyli/bootstrap-flask#73]
通过pip 安装模块，在bootstrap文件夹下没有table.html文件，因此这个模块的example的Table分页是打不开的，显示错误。找不到bootstrap/table.html.
我手动将table.html下载至bootstrap文件夹下，打开example的Table分页仍然显示错误，
jinja2.exceptions.UndefinedError
jinja2.exceptions.UndefinedError: 'get_table_titles' is undefined

python3.7
Bootstrap-Flask==1.3.2

**Comment by greyli** [comment]
Duplicate of #74.
