### ISSUE TITLE
Missing  templates/bootstrap/table.html from Pypi version

### ISSUE THREAD

**Issue by holeybit** [greyli/bootstrap-flask#74]
Looks like the files from https://pypi.org/project/Bootstrap-Flask/1.3.2/ are missing the /templates/bootstrap/tables.html

```
➜  Bootstrap-Flask-1.3.2 tree flask_bootstrap/templates
flask_bootstrap/templates
└── bootstrap
    ├── form.html
    ├── nav.html
    ├── pagination.html
    └── utils.html

1 directory, 4 files
```

Workaround:

```
pip install git+https://github.com/greyli/bootstrap-flask.git
```

**Comment by greyli** [comment]
Thanks for reporting on this. I just released [1.4](https://pypi.org/project/Bootstrap-Flask/) to make `render_table` available:
```
pip install -U bootstrap-flask
```
Give it a try, any feedback is welcome.
