### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by michaelbukachi** [greyli/bootstrap-flask#75]
`for k in data[0].__table__.columns._data.keys():` from get_table_titles assumes the `data` is not empty. An `IndexError` is thrown for empty tables.

Maybe add the following line to the top of the function:
```
if not data:
    return []
```

**Comment by greyli** [comment]
Thank you for your feedback, fixed in https://github.com/greyli/bootstrap-flask/commit/cfb59affd7b40fabace9632fc20294b9f286d534.
