### ISSUE TITLE
Add action column to render_table

### ISSUE THREAD

**Issue by michaelbukachi** [greyli/bootstrap-flask#76]
Is it possible to  add an action column to the `render_table` which will render view/delete icons. I'm thinking of adding a `show_actions` parameter which will have a default value of `False`. Then we can add two extra parameters `view_url` and `delete_url`. If the urls are provided,  they are automatically concatenated with the `primary_key` value. Willing to do a PR for this.

**Comment by greyli** [comment]
It's a useful feature, happy to see this implemented. Maybe we can support three parameters separately for view、edit and delete, and just let the user pass the complete URL (since some user may not put the ID at the end of the URL).

**Comment by michaelbukachi** [comment]
Cool. Let me work on it.

**Comment by greyli** [comment]
Implemented in #77 and #80, closing now.
