### ISSUE TITLE
jQuery sources aren't fetched

### ISSUE THREAD

**Issue by tylerjl** [greyli/bootstrap-flask#8]
With the default load_js macro, the URL that gets rendered doesn't match any sources shipped by this project - although the versioned file exists, it looks for the simply-named minified javascript:

<img width="391" alt="screen shot 2018-08-06 at 10 23 29 pm" src="https://user-images.githubusercontent.com/1733846/43754312-65cdc5a2-99c7-11e8-973c-7c10ccc188e7.png">

Seems like either constructing the versioned jquery file or copying/linking the versioned jquery minified source into the unversioned path would work.

**Comment by greyli** [comment]
Thanks for the feedback, I'll fix it and create a new release today.

**Comment by greyli** [comment]
Fixed in version [1.0.6](https://github.com/greyli/bootstrap-flask/releases/tag/1.0.6).
