### ISSUE TITLE
render_field checkbox label

### ISSUE THREAD

**Issue by ziddey** [greyli/bootstrap-flask#84]
https://github.com/greyli/bootstrap-flask/blob/daaf1c59d5e3d26396cb3091c609f4122cde8170/flask_bootstrap/templates/bootstrap/form.html#L48-L64

I'm curious why is the field label text rendered by itself with an empty id-less label? Also, why always have the `is_invalid` class?

Are there any issues doing the same as for other input types, ie simply: `{{ field.label(class="form-check-label")|safe }}`

And if `is_invalid` is desired when `field.errors`, maybe a jinja if clause for it?

**Comment by greyli** [comment]
Thank you, fixed with https://github.com/greyli/bootstrap-flask/commit/c71b8b76e66fa62da22e8fc6b5583b2fbe5f1c58.
